import type { Metadata } from "next";

import "./globals.css";

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import Script from "next/script";

import QueryClientProviderWrapper from "@/providers/QueryClient";
import ScreenSizeIndicator from "@/components/shared/ScreenSizeIndicator";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Tracer EVD for IPPOG Masterclasses",
  description: "Generated by Tracer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Google Analytics */}
      <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-1W2C5LEK3M"
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-1W2C5LEK3M');
        `}
      </Script>

      <body className="antialiased">
        <QueryClientProviderWrapper>
          <div className="flex flex-col">{children}</div>
          <ScreenSizeIndicator />
          <ReactQueryDevtools />
          <Toaster />
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
